services:
  bot:
    container_name: conferee_tg_bot
    build:
      context: .
    env_file:
      - ~/config/.env
    volumes:
      - ~/logs:/app/logs
    restart: unless-stopped
    labels:
      - group=confereebot
      - dev.dozzle.name=tgbot
