services:
  bot:
    container_name: conferee_tg_bot
    build:
      context: .
    depends_on:
      - mongodb
    env_file:
      - conferee_tg_bot.env
    volumes:
      - ~/conferee_logs:/app/logs
    restart: unless-stopped
    labels:
      - group=confereebot
      - dev.dozzle.name=tgbot

  mongodb:
    container_name: conferee_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    labels:
      - group=confereebot

volumes:
  mongodb_data:
