services:
  bot:
    container_name: conferee_tg_bot
    build:
      context: .
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    labels:
      - group=confereebot
      - dev.dozzle.name=tgbot

  mongodb:
    container_name: conferee_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    labels:
      - group=confereebot

volumes:
  mongodb_data:
